---
- name: Configure WebServers
  hosts: 51.120.244.101
  become: True
  tasks:
    - name: Install Nginx
      apt: name=nginx
    - name: Copy config file Nginx
      copy: src=/Jenkins/nginx.conf dest=/etc/nginx
    - name: Copy site index.html
      copy: src=/Jenkins/index.html dest=/var/www/html
    - name: restart Nginx
      service: name=nginx state=restarted
